apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-metrics-config
  namespace: alloy-metrics 
data:
  config.alloy: |-

    discovery.kubernetes "pod" {
      role = "pod"
    }
    prometheus.scrape "pods" {
      targets    = discovery.kubernetes.pod.targets
      forward_to = [prometheus.remote_write.mimir.receiver]
      scrape_interval = "15s"
    }
    prometheus.remote_write "mimir" {
      endpoint {
        url = "http://mimir-gateway.mimir.svc.cluster.local/api/v1/push"
        headers = {
          "X-Scope-OrgID" = "pods"
        }
        tls_config {
          insecure_skip_verify = true
        }
      }
    }
